### ISSUE TITLE
Mod doesn't show up in Mod menu

### ISSUE THREAD

**Issue by LolMakesStuff** [fadeinside/s3air-achievements-plus#19]
Hello, I just downloaded the mod, and for some reason it doesn't show up in the mod menu. 
![image](https://user-images.githubusercontent.com/78550458/179756450-26c4f342-0889-4121-a2a5-5882bd211c64.png)
![image](https://user-images.githubusercontent.com/78550458/179756653-e901a023-b85b-4b5b-b578-2ac2175e2000.png)
I have no idea what's happening, is there a fix, or do I have to redownload the mod somewhere else?

**Comment by LolMakesStuff** [comment]
Update: the mod requires an newer version, gonna update to the latest version.

**Comment by LolMakesStuff** [comment]
Update: Turn's out I was just on the stable version, the preview version works with the mod.

**Comment by fadeinside** [comment]
Good boy
