### ISSUE TITLE
Achievements can be acquired in act select (in latest test version)

### ISSUE THREAD

**Issue by TimerBunneh** [fadeinside/s3air-achievements-plus#25]
I'm not sure what to say other than what's already in the title above. The version I'm using is 23.05.14.01.

**Comment by fadeinside** [comment]
Hi, is this mod similar to the one being actively developed? I haven't been involved in AIR mod development for a long time, so don't expect that to change soon

**Comment by TimerBunneh** [comment]
I didn't realize there was another. I only know of this version.
